### PR TITLE
Shell/5494

### PR DESCRIPTION
**Pull request by mcatanzaro**
[endlessm/eos-shell#5494]

### CODE REVIEW

**Comment by dbnicholson** [comment]
@mcatanzaro I didn't expect these to be part of the PR, but I'm all for it if you feel confident.

**Comment by mcatanzaro** [comment]
I tested this and found it has no effect on upgrades. Since that is what I was attempting to fix with these ineffectual changes, I suggest reverting to the upstream configuration.

It might affect `systemctl reload` (not tested), but I think if you run `systemctl reload gdm` and gdm restarts, that is not so horribly unexpected.

**Comment by dbnicholson** [comment]
Yeah, I guess what I'm worried about is that we're focused on debian package upgrades (which our users would never see), but I want to make sure we don't regress the normal runtime systemd/gdm behavior.

**Comment by mcatanzaro** [comment]
Users have never gotten these changes yet -- they are only in master -- so reverting them means there is no chance of regression, whereas keeping the changes means there is potential for some unforeseen regression. Most likely it will make zero difference, but reverting is somewhat safer.

The most likely potential issue is that some hypothetical unit that depends on GDM's D-Bus interface gets started before GDM is ready and then crashes. If we were to add such a hypothetical unit in the future, it could break; reverting these commits will avoid that problem.

**Comment by dbnicholson** [comment]
OK, I didn't realize these changes had only been in recently. I thought they were in our gdm from before.

**Pull request merged**
